# Generated by Django 4.2.23 on 2025-08-20 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arquivo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url_pdf', models.URLField()),
                ('mes_publicacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
