# Generated by Django 4.2.23 on 2025-08-21 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquivos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivo',
            name='mes_publicacao',
            field=models.CharField(db_index=True, max_length=2),
        ),
    ]
